
  --t-add-p: 0%;
  --t-add-px-10: 0px;
  --t-add-px-1: 0px;
  --r-add-p: 0%;
  --r-add-px-10: 0px;
  --r-add-px-1: 0px;
  --b-add-p: 0%;
  --b-add-px-10: 0px;
  --b-add-px-1: 0px;
  --l-add-p: 0%;
  --l-add-px-10: 0px;
  --l-add-px-1: 0px;