.clr-main   { color: var(--color-main);   }
.clr-main-h { color: var(--color-main-h); }
.clr-sub    { color: var(--color-sub);    }
.clr-sub-h  { color: var(--color-sub-h);  }
.clr-acnt   { color: var(--color-acnt);   }
.clr-acnt-h { color: var(--color-acnt-h); }
.clr-black  { color: var(--color-black);  }
.clr-g9     { color: var(--color-g9);     }
.clr-g8     { color: var(--color-g8);     }
.clr-g7     { color: var(--color-g7);     }
.clr-g6     { color: var(--color-g6);     }
.clr-g5     { color: var(--color-g5);     }
.clr-g4     { color: var(--color-g4);     }
.clr-g3     { color: var(--color-g3);     }
.clr-g2     { color: var(--color-g2);     }
.clr-g1     { color: var(--color-g1);     }
.clr-white  { color: var(--color-white);  }
.clr-no     { color: var(--color-no);     }