.bg-main   { background-color: var(--color-main); }
.bg-main-h { background-color: var(--color-main-h); }
.bg-sub    { background-color: var(--color-sub); }
.bg-sub-h  { background-color: var(--color-sub-h); }
.bg-black  { background-color: var(--color-black); }
.bg-white  { background-color: var(--color-white); }
.bg-g9     { background-color: var(--color-g9); }
.bg-g8     { background-color: var(--color-g8); }
.bg-g7     { background-color: var(--color-g7); }
.bg-g6     { background-color: var(--color-g6); }
.bg-g5     { background-color: var(--color-g5); }
.bg-g4     { background-color: var(--color-g4); }
.bg-g3     { background-color: var(--color-g3); }
.bg-g2     { background-color: var(--color-g2); }
.bg-g1     { background-color: var(--color-g1); }