.hr-bg-main   { --hr-bg: var(--color-main);   }
.hr-bg-main-h { --hr-bg: var(--color-main-h); }
.hr-bg-sub    { --hr-bg: var(--color-sub);    }
.hr-bg-sub-h  { --hr-bg: var(--color-sub-h);  }
.hr-bg-acnt   { --hr-bg: var(--color-acnt);   }
.hr-bg-acnt-h { --hr-bg: var(--color-acnt-h); }
.hr-bg-black  { --hr-bg: var(--color-black);  }
.hr-bg-g9     { --hr-bg: var(--color-g9);     }
.hr-bg-g8     { --hr-bg: var(--color-g8);     }
.hr-bg-g7     { --hr-bg: var(--color-g7);     }
.hr-bg-g6     { --hr-bg: var(--color-g6);     }
.hr-bg-g5     { --hr-bg: var(--color-g5);     }
.hr-bg-g4     { --hr-bg: var(--color-g4);     }
.hr-bg-g3     { --hr-bg: var(--color-g3);     }
.hr-bg-g2     { --hr-bg: var(--color-g2);     }
.hr-bg-g1     { --hr-bg: var(--color-g1);     }
.hr-bg-white  { --hr-bg: var(--color-white);  }
.hr-bg-0      { --hr-bg: var(--color-0);      }