.chs-bg-main   { --chs-bg: var(--color-main);   }
.chs-bg-main-h { --chs-bg: var(--color-main-h); }
.chs-bg-sub    { --chs-bg: var(--color-sub);    }
.chs-bg-sub-h  { --chs-bg: var(--color-sub-h);  }
.chs-bg-acnt   { --chs-bg: var(--color-acnt);   }
.chs-bg-acnt-h { --chs-bg: var(--color-acnt-h); }
.chs-bg-black  { --chs-bg: var(--color-black);  }
.chs-bg-g9     { --chs-bg: var(--color-g9);     }
.chs-bg-g8     { --chs-bg: var(--color-g8);     }
.chs-bg-g7     { --chs-bg: var(--color-g7);     }
.chs-bg-g6     { --chs-bg: var(--color-g6);     }
.chs-bg-g5     { --chs-bg: var(--color-g5);     }
.chs-bg-g4     { --chs-bg: var(--color-g4);     }
.chs-bg-g3     { --chs-bg: var(--color-g3);     }
.chs-bg-g2     { --chs-bg: var(--color-g2);     }
.chs-bg-g1     { --chs-bg: var(--color-g1);     }
.chs-bg-white  { --chs-bg: var(--color-white);  }
.chs-bg-0      { --chs-bg: var(--color-0);      }