.chs-clr-main   { --chs-clr: var(--color-main);   }
.chs-clr-main-h { --chs-clr: var(--color-main-h); }
.chs-clr-sub    { --chs-clr: var(--color-sub);    }
.chs-clr-sub-h  { --chs-clr: var(--color-sub-h);  }
.chs-clr-acnt   { --chs-clr: var(--color-acnt);   }
.chs-clr-acnt-h { --chs-clr: var(--color-acnt-h); }
.chs-clr-black  { --chs-clr: var(--color-black);  }
.chs-clr-g9     { --chs-clr: var(--color-g9);     }
.chs-clr-g8     { --chs-clr: var(--color-g8);     }
.chs-clr-g7     { --chs-clr: var(--color-g7);     }
.chs-clr-g6     { --chs-clr: var(--color-g6);     }
.chs-clr-g5     { --chs-clr: var(--color-g5);     }
.chs-clr-g4     { --chs-clr: var(--color-g4);     }
.chs-clr-g3     { --chs-clr: var(--color-g3);     }
.chs-clr-g2     { --chs-clr: var(--color-g2);     }
.chs-clr-g1     { --chs-clr: var(--color-g1);     }
.chs-clr-white  { --chs-clr: var(--color-white);  }
.chs-clr-0      { --chs-clr: var(--color-0);      }