.chr-bg-main   { --chr-bg: var(--color-main);   }
.chr-bg-main-h { --chr-bg: var(--color-main-h); }
.chr-bg-sub    { --chr-bg: var(--color-sub);    }
.chr-bg-sub-h  { --chr-bg: var(--color-sub-h);  }
.chr-bg-acnt   { --chr-bg: var(--color-acnt);   }
.chr-bg-acnt-h { --chr-bg: var(--color-acnt-h); }
.chr-bg-black  { --chr-bg: var(--color-black);  }
.chr-bg-g9     { --chr-bg: var(--color-g9);     }
.chr-bg-g8     { --chr-bg: var(--color-g8);     }
.chr-bg-g7     { --chr-bg: var(--color-g7);     }
.chr-bg-g6     { --chr-bg: var(--color-g6);     }
.chr-bg-g5     { --chr-bg: var(--color-g5);     }
.chr-bg-g4     { --chr-bg: var(--color-g4);     }
.chr-bg-g3     { --chr-bg: var(--color-g3);     }
.chr-bg-g2     { --chr-bg: var(--color-g2);     }
.chr-bg-g1     { --chr-bg: var(--color-g1);     }
.chr-bg-white  { --chr-bg: var(--color-white);  }
.chr-bg-0      { --chr-bg: var(--color-0);      }