.hs-bg-main   { --hs-bg: var(--color-main);   }
.hs-bg-main-h { --hs-bg: var(--color-main-h); }
.hs-bg-sub    { --hs-bg: var(--color-sub);    }
.hs-bg-sub-h  { --hs-bg: var(--color-sub-h);  }
.hs-bg-acnt   { --hs-bg: var(--color-acnt);   }
.hs-bg-acnt-h { --hs-bg: var(--color-acnt-h); }
.hs-bg-black  { --hs-bg: var(--color-black);  }
.hs-bg-g9     { --hs-bg: var(--color-g9);     }
.hs-bg-g8     { --hs-bg: var(--color-g8);     }
.hs-bg-g7     { --hs-bg: var(--color-g7);     }
.hs-bg-g6     { --hs-bg: var(--color-g6);     }
.hs-bg-g5     { --hs-bg: var(--color-g5);     }
.hs-bg-g4     { --hs-bg: var(--color-g4);     }
.hs-bg-g3     { --hs-bg: var(--color-g3);     }
.hs-bg-g2     { --hs-bg: var(--color-g2);     }
.hs-bg-g1     { --hs-bg: var(--color-g1);     }
.hs-bg-white  { --hs-bg: var(--color-white);  }
.hs-bg-0      { --hs-bg: var(--color-0);      }