.hr-clr-main   { --hr-clr: var(--color-main);   }
.hr-clr-main-h { --hr-clr: var(--color-main-h); }
.hr-clr-sub    { --hr-clr: var(--color-sub);    }
.hr-clr-sub-h  { --hr-clr: var(--color-sub-h);  }
.hr-clr-acnt   { --hr-clr: var(--color-acnt);   }
.hr-clr-acnt-h { --hr-clr: var(--color-acnt-h); }
.hr-clr-black  { --hr-clr: var(--color-black);  }
.hr-clr-g9     { --hr-clr: var(--color-g9);     }
.hr-clr-g8     { --hr-clr: var(--color-g8);     }
.hr-clr-g7     { --hr-clr: var(--color-g7);     }
.hr-clr-g6     { --hr-clr: var(--color-g6);     }
.hr-clr-g5     { --hr-clr: var(--color-g5);     }
.hr-clr-g4     { --hr-clr: var(--color-g4);     }
.hr-clr-g3     { --hr-clr: var(--color-g3);     }
.hr-clr-g2     { --hr-clr: var(--color-g2);     }
.hr-clr-g1     { --hr-clr: var(--color-g1);     }
.hr-clr-white  { --hr-clr: var(--color-white);  }
.hr-clr-0      { --hr-clr: var(--color-0);      }