.hs-clr-main   { --hs-clr: var(--color-main);   }
.hs-clr-main-h { --hs-clr: var(--color-main-h); }
.hs-clr-sub    { --hs-clr: var(--color-sub);    }
.hs-clr-sub-h  { --hs-clr: var(--color-sub-h);  }
.hs-clr-acnt   { --hs-clr: var(--color-acnt);   }
.hs-clr-acnt-h { --hs-clr: var(--color-acnt-h); }
.hs-clr-black  { --hs-clr: var(--color-black);  }
.hs-clr-g9     { --hs-clr: var(--color-g9);     }
.hs-clr-g8     { --hs-clr: var(--color-g8);     }
.hs-clr-g7     { --hs-clr: var(--color-g7);     }
.hs-clr-g6     { --hs-clr: var(--color-g6);     }
.hs-clr-g5     { --hs-clr: var(--color-g5);     }
.hs-clr-g4     { --hs-clr: var(--color-g4);     }
.hs-clr-g3     { --hs-clr: var(--color-g3);     }
.hs-clr-g2     { --hs-clr: var(--color-g2);     }
.hs-clr-g1     { --hs-clr: var(--color-g1);     }
.hs-clr-white  { --hs-clr: var(--color-white);  }
.hs-clr-0      { --hs-clr: var(--color-0);      }