.chr-clr-main   { --chr-clr: var(--color-main);   }
.chr-clr-main-h { --chr-clr: var(--color-main-h); }
.chr-clr-sub    { --chr-clr: var(--color-sub);    }
.chr-clr-sub-h  { --chr-clr: var(--color-sub-h);  }
.chr-clr-acnt   { --chr-clr: var(--color-acnt);   }
.chr-clr-acnt-h { --chr-clr: var(--color-acnt-h); }
.chr-clr-black  { --chr-clr: var(--color-black);  }
.chr-clr-g9     { --chr-clr: var(--color-g9);     }
.chr-clr-g8     { --chr-clr: var(--color-g8);     }
.chr-clr-g7     { --chr-clr: var(--color-g7);     }
.chr-clr-g6     { --chr-clr: var(--color-g6);     }
.chr-clr-g5     { --chr-clr: var(--color-g5);     }
.chr-clr-g4     { --chr-clr: var(--color-g4);     }
.chr-clr-g3     { --chr-clr: var(--color-g3);     }
.chr-clr-g2     { --chr-clr: var(--color-g2);     }
.chr-clr-g1     { --chr-clr: var(--color-g1);     }
.chr-clr-white  { --chr-clr: var(--color-white);  }
.chr-clr-0      { --chr-clr: var(--color-0);      }