.cho\:brightness-0p   { --cho-brightness: 0%;   }
.cho\:brightness-10p  { --cho-brightness: 10%;  }
.cho\:brightness-20p  { --cho-brightness: 20%;  }
.cho\:brightness-30p  { --cho-brightness: 30%;  }
.cho\:brightness-40p  { --cho-brightness: 40%;  }
.cho\:brightness-50p  { --cho-brightness: 50%;  }
.cho\:brightness-60p  { --cho-brightness: 60%;  }
.cho\:brightness-70p  { --cho-brightness: 70%;  }
.cho\:brightness-80p  { --cho-brightness: 80%;  }
.cho\:brightness-90p  { --cho-brightness: 90%;  }
.cho\:brightness-100p { --cho-brightness: 100%; }
.cho\:brightness-110p { --cho-brightness: 110%; }
.cho\:brightness-120p { --cho-brightness: 120%; }
.cho\:brightness-130p { --cho-brightness: 130%; }
.cho\:brightness-140p { --cho-brightness: 140%; }
.cho\:brightness-150p { --cho-brightness: 150%; }
.cho\:brightness-160p { --cho-brightness: 160%; }
.cho\:brightness-170p { --cho-brightness: 170%; }
.cho\:brightness-180p { --cho-brightness: 180%; }
.cho\:brightness-190p { --cho-brightness: 190%; }
.cho\:brightness-200p { --cho-brightness: 200%; }