.h-add-1max { --h-a-max: 1px; }
.h-add-2max { --h-a-max: 2px; }
.h-add-3max { --h-a-max: 3px; }
.h-add-4max { --h-a-max: 4px; }
.h-add-5max { --h-a-max: 5px; }
.h-add-6max { --h-a-max: 6px; }
.h-add-7max { --h-a-max: 7px; }
.h-add-8max { --h-a-max: 8px; }
.h-add-9max { --h-a-max: 9px; }