.r-add-1px { --r-add-px-1: 1px; }
.r-add-2px { --r-add-px-1: 2px; }
.r-add-3px { --r-add-px-1: 3px; }
.r-add-4px { --r-add-px-1: 4px; }
.r-add-5px { --r-add-px-1: 5px; }
.r-add-6px { --r-add-px-1: 6px; }
.r-add-7px { --r-add-px-1: 7px; }
.r-add-8px { --r-add-px-1: 8px; }
.r-add-9px { --r-add-px-1: 9px; }