.slides-1  { --yd-slides: 1;  }
.slides-2  { --yd-slides: 2;  }
.slides-3  { --yd-slides: 3;  }
.slides-4  { --yd-slides: 4;  }
.slides-5  { --yd-slides: 5;  }
.slides-6  { --yd-slides: 6;  }
.slides-7  { --yd-slides: 7;  }
.slides-8  { --yd-slides: 8;  }
.slides-9  { --yd-slides: 9;  }
.slides-10 { --yd-slides: 10; }
.slides-11 { --yd-slides: 11; }
.slides-12 { --yd-slides: 12; }