.tb-add-1px { --tb-add-px: 1px; }
.tb-add-2px { --tb-add-px: 2px; }
.tb-add-3px { --tb-add-px: 3px; }
.tb-add-4px { --tb-add-px: 4px; }
.tb-add-5px { --tb-add-px: 5px; }
.tb-add-6px { --tb-add-px: 6px; }
.tb-add-7px { --tb-add-px: 7px; }
.tb-add-8px { --tb-add-px: 8px; }
.tb-add-9px { --tb-add-px: 9px; }