.hs-rotate-10deg  { --hs-rotate: calc(10deg + var(--hs-rotate-add));  }
.hs-rotate-20deg  { --hs-rotate: calc(20deg + var(--hs-rotate-add));  }
.hs-rotate-30deg  { --hs-rotate: calc(30deg + var(--hs-rotate-add));  }
.hs-rotate-40deg  { --hs-rotate: calc(40deg + var(--hs-rotate-add));  }
.hs-rotate-50deg  { --hs-rotate: calc(50deg + var(--hs-rotate-add));  }
.hs-rotate-60deg  { --hs-rotate: calc(60deg + var(--hs-rotate-add));  }
.hs-rotate-70deg  { --hs-rotate: calc(70deg + var(--hs-rotate-add));  }
.hs-rotate-80deg  { --hs-rotate: calc(80deg + var(--hs-rotate-add));  }
.hs-rotate-90deg  { --hs-rotate: calc(90deg + var(--hs-rotate-add));  }
.hs-rotate-100deg { --hs-rotate: calc(100deg + var(--hs-rotate-add)); }
.hs-rotate-110deg { --hs-rotate: calc(110deg + var(--hs-rotate-add)); }
.hs-rotate-120deg { --hs-rotate: calc(120deg + var(--hs-rotate-add)); }
.hs-rotate-130deg { --hs-rotate: calc(130deg + var(--hs-rotate-add)); }
.hs-rotate-140deg { --hs-rotate: calc(140deg + var(--hs-rotate-add)); }
.hs-rotate-150deg { --hs-rotate: calc(150deg + var(--hs-rotate-add)); }
.hs-rotate-160deg { --hs-rotate: calc(160deg + var(--hs-rotate-add)); }
.hs-rotate-170deg { --hs-rotate: calc(170deg + var(--hs-rotate-add)); }
.hs-rotate-180deg { --hs-rotate: calc(180deg + var(--hs-rotate-add)); }
.hs-rotate-190deg { --hs-rotate: calc(190deg + var(--hs-rotate-add)); }
.hs-rotate-200deg { --hs-rotate: calc(200deg + var(--hs-rotate-add)); }
.hs-rotate-210deg { --hs-rotate: calc(210deg + var(--hs-rotate-add)); }
.hs-rotate-220deg { --hs-rotate: calc(220deg + var(--hs-rotate-add)); }
.hs-rotate-230deg { --hs-rotate: calc(230deg + var(--hs-rotate-add)); }
.hs-rotate-240deg { --hs-rotate: calc(240deg + var(--hs-rotate-add)); }
.hs-rotate-250deg { --hs-rotate: calc(250deg + var(--hs-rotate-add)); }
.hs-rotate-260deg { --hs-rotate: calc(260deg + var(--hs-rotate-add)); }
.hs-rotate-270deg { --hs-rotate: calc(270deg + var(--hs-rotate-add)); }
.hs-rotate-280deg { --hs-rotate: calc(280deg + var(--hs-rotate-add)); }
.hs-rotate-290deg { --hs-rotate: calc(290deg + var(--hs-rotate-add)); }
.hs-rotate-300deg { --hs-rotate: calc(300deg + var(--hs-rotate-add)); }
.hs-rotate-310deg { --hs-rotate: calc(310deg + var(--hs-rotate-add)); }
.hs-rotate-320deg { --hs-rotate: calc(320deg + var(--hs-rotate-add)); }
.hs-rotate-330deg { --hs-rotate: calc(330deg + var(--hs-rotate-add)); }
.hs-rotate-340deg { --hs-rotate: calc(340deg + var(--hs-rotate-add)); }
.hs-rotate-350deg { --hs-rotate: calc(350deg + var(--hs-rotate-add)); }
.hs-rotate-360deg { --hs-rotate: calc(360deg + var(--hs-rotate-add)); }
.hs-rotate-0deg   { --hs-rotate: 0deg;                                }