.chs-rotate-10deg  { --chs-rotate: calc(10deg + var(--chs-rotate-add));  }
.chs-rotate-20deg  { --chs-rotate: calc(20deg + var(--chs-rotate-add));  }
.chs-rotate-30deg  { --chs-rotate: calc(30deg + var(--chs-rotate-add));  }
.chs-rotate-40deg  { --chs-rotate: calc(40deg + var(--chs-rotate-add));  }
.chs-rotate-50deg  { --chs-rotate: calc(50deg + var(--chs-rotate-add));  }
.chs-rotate-60deg  { --chs-rotate: calc(60deg + var(--chs-rotate-add));  }
.chs-rotate-70deg  { --chs-rotate: calc(70deg + var(--chs-rotate-add));  }
.chs-rotate-80deg  { --chs-rotate: calc(80deg + var(--chs-rotate-add));  }
.chs-rotate-90deg  { --chs-rotate: calc(90deg + var(--chs-rotate-add));  }
.chs-rotate-100deg { --chs-rotate: calc(100deg + var(--chs-rotate-add)); }
.chs-rotate-110deg { --chs-rotate: calc(110deg + var(--chs-rotate-add)); }
.chs-rotate-120deg { --chs-rotate: calc(120deg + var(--chs-rotate-add)); }
.chs-rotate-130deg { --chs-rotate: calc(130deg + var(--chs-rotate-add)); }
.chs-rotate-140deg { --chs-rotate: calc(140deg + var(--chs-rotate-add)); }
.chs-rotate-150deg { --chs-rotate: calc(150deg + var(--chs-rotate-add)); }
.chs-rotate-160deg { --chs-rotate: calc(160deg + var(--chs-rotate-add)); }
.chs-rotate-170deg { --chs-rotate: calc(170deg + var(--chs-rotate-add)); }
.chs-rotate-180deg { --chs-rotate: calc(180deg + var(--chs-rotate-add)); }
.chs-rotate-190deg { --chs-rotate: calc(190deg + var(--chs-rotate-add)); }
.chs-rotate-200deg { --chs-rotate: calc(200deg + var(--chs-rotate-add)); }
.chs-rotate-210deg { --chs-rotate: calc(210deg + var(--chs-rotate-add)); }
.chs-rotate-220deg { --chs-rotate: calc(220deg + var(--chs-rotate-add)); }
.chs-rotate-230deg { --chs-rotate: calc(230deg + var(--chs-rotate-add)); }
.chs-rotate-240deg { --chs-rotate: calc(240deg + var(--chs-rotate-add)); }
.chs-rotate-250deg { --chs-rotate: calc(250deg + var(--chs-rotate-add)); }
.chs-rotate-260deg { --chs-rotate: calc(260deg + var(--chs-rotate-add)); }
.chs-rotate-270deg { --chs-rotate: calc(270deg + var(--chs-rotate-add)); }
.chs-rotate-280deg { --chs-rotate: calc(280deg + var(--chs-rotate-add)); }
.chs-rotate-290deg { --chs-rotate: calc(290deg + var(--chs-rotate-add)); }
.chs-rotate-300deg { --chs-rotate: calc(300deg + var(--chs-rotate-add)); }
.chs-rotate-310deg { --chs-rotate: calc(310deg + var(--chs-rotate-add)); }
.chs-rotate-320deg { --chs-rotate: calc(320deg + var(--chs-rotate-add)); }
.chs-rotate-330deg { --chs-rotate: calc(330deg + var(--chs-rotate-add)); }
.chs-rotate-340deg { --chs-rotate: calc(340deg + var(--chs-rotate-add)); }
.chs-rotate-350deg { --chs-rotate: calc(350deg + var(--chs-rotate-add)); }
.chs-rotate-360deg { --chs-rotate: calc(360deg + var(--chs-rotate-add)); }
.chs-rotate-0deg   { --chs-rotate: 0deg;                                 }