.rotate-10deg  { --rotate-value: calc(10deg + var(--rotate-add));  }
.rotate-20deg  { --rotate-value: calc(20deg + var(--rotate-add));  }
.rotate-30deg  { --rotate-value: calc(30deg + var(--rotate-add));  }
.rotate-40deg  { --rotate-value: calc(40deg + var(--rotate-add));  }
.rotate-50deg  { --rotate-value: calc(50deg + var(--rotate-add));  }
.rotate-60deg  { --rotate-value: calc(60deg + var(--rotate-add));  }
.rotate-70deg  { --rotate-value: calc(70deg + var(--rotate-add));  }
.rotate-80deg  { --rotate-value: calc(80deg + var(--rotate-add));  }
.rotate-90deg  { --rotate-value: calc(90deg + var(--rotate-add));  }
.rotate-100deg { --rotate-value: calc(100deg + var(--rotate-add)); }
.rotate-110deg { --rotate-value: calc(110deg + var(--rotate-add)); }
.rotate-120deg { --rotate-value: calc(120deg + var(--rotate-add)); }
.rotate-130deg { --rotate-value: calc(130deg + var(--rotate-add)); }
.rotate-140deg { --rotate-value: calc(140deg + var(--rotate-add)); }
.rotate-150deg { --rotate-value: calc(150deg + var(--rotate-add)); }
.rotate-160deg { --rotate-value: calc(160deg + var(--rotate-add)); }
.rotate-170deg { --rotate-value: calc(170deg + var(--rotate-add)); }
.rotate-180deg { --rotate-value: calc(180deg + var(--rotate-add)); }
.rotate-190deg { --rotate-value: calc(190deg + var(--rotate-add)); }
.rotate-200deg { --rotate-value: calc(200deg + var(--rotate-add)); }
.rotate-210deg { --rotate-value: calc(210deg + var(--rotate-add)); }
.rotate-220deg { --rotate-value: calc(220deg + var(--rotate-add)); }
.rotate-230deg { --rotate-value: calc(230deg + var(--rotate-add)); }
.rotate-240deg { --rotate-value: calc(240deg + var(--rotate-add)); }
.rotate-250deg { --rotate-value: calc(250deg + var(--rotate-add)); }
.rotate-260deg { --rotate-value: calc(260deg + var(--rotate-add)); }
.rotate-270deg { --rotate-value: calc(270deg + var(--rotate-add)); }
.rotate-280deg { --rotate-value: calc(280deg + var(--rotate-add)); }
.rotate-290deg { --rotate-value: calc(290deg + var(--rotate-add)); }
.rotate-300deg { --rotate-value: calc(300deg + var(--rotate-add)); }
.rotate-310deg { --rotate-value: calc(310deg + var(--rotate-add)); }
.rotate-320deg { --rotate-value: calc(320deg + var(--rotate-add)); }
.rotate-330deg { --rotate-value: calc(330deg + var(--rotate-add)); }
.rotate-340deg { --rotate-value: calc(340deg + var(--rotate-add)); }
.rotate-350deg { --rotate-value: calc(350deg + var(--rotate-add)); }
.rotate-360deg { --rotate-value: calc(360deg + var(--rotate-add)); }
.rotate-0deg   { --rotate-value: 0deg;                             }