.wsp--10 { word-spacing: -10px; }
.wsp--9  { word-spacing: -9px;  }
.wsp--8  { word-spacing: -8px;  }
.wsp--7  { word-spacing: -7px;  }
.wsp--6  { word-spacing: -6px;  }
.wsp--5  { word-spacing: -5px;  }
.wsp--4  { word-spacing: -4px;  }
.wsp--3  { word-spacing: -3px;  }
.wsp--2  { word-spacing: -2px;  }
.wsp--1  { word-spacing: -1px;  }
.wsp-0   { word-spacing: 0;     }
.wsp-1   { word-spacing: 1px;   }
.wsp-2   { word-spacing: 2px;   }
.wsp-3   { word-spacing: 3px;   }
.wsp-4   { word-spacing: 4px;   }
.wsp-5   { word-spacing: 5px;   }
.wsp-6   { word-spacing: 6px;   }
.wsp-7   { word-spacing: 7px;   }
.wsp-8   { word-spacing: 8px;   }
.wsp-9   { word-spacing: 9px;   }
.wsp-10  { word-spacing: 10px;  }