.lsp--10 { letter-spacing: -10px; }
.lsp--9  { letter-spacing: -9px;  }
.lsp--8  { letter-spacing: -8px;  }
.lsp--7  { letter-spacing: -7px;  }
.lsp--6  { letter-spacing: -6px;  }
.lsp--5  { letter-spacing: -5px;  }
.lsp--4  { letter-spacing: -4px;  }
.lsp--3  { letter-spacing: -3px;  }
.lsp--2  { letter-spacing: -2px;  }
.lsp--1  { letter-spacing: -1px;  }
.lsp-0   { letter-spacing: 0;     }
.lsp-1   { letter-spacing: 1px;   }
.lsp-2   { letter-spacing: 2px;   }
.lsp-3   { letter-spacing: 3px;   }
.lsp-4   { letter-spacing: 4px;   }
.lsp-5   { letter-spacing: 5px;   }
.lsp-6   { letter-spacing: 6px;   }
.lsp-7   { letter-spacing: 7px;   }
.lsp-8   { letter-spacing: 8px;   }
.lsp-9   { letter-spacing: 9px;   }
.lsp-10  { letter-spacing: 10px;  }