.w-add-1max { --w-a-max: 1px; }
.w-add-2max { --w-a-max: 2px; }
.w-add-3max { --w-a-max: 3px; }
.w-add-4max { --w-a-max: 4px; }
.w-add-5max { --w-a-max: 5px; }
.w-add-6max { --w-a-max: 6px; }
.w-add-7max { --w-a-max: 7px; }
.w-add-8max { --w-a-max: 8px; }
.w-add-9max { --w-a-max: 9px; }