.w-add-1vw { --w-a-vw: 1vw; }
.w-add-2vw { --w-a-vw: 2vw; }
.w-add-3vw { --w-a-vw: 3vw; }
.w-add-4vw { --w-a-vw: 4vw; }
.w-add-5vw { --w-a-vw: 5vw; }
.w-add-6vw { --w-a-vw: 6vw; }
.w-add-7vw { --w-a-vw: 7vw; }
.w-add-8vw { --w-a-vw: 8vw; }
.w-add-9vw { --w-a-vw: 9vw; }