.w-add-1min { --w-add-min-1: 1px; }
.w-add-2min { --w-add-min-1: 2px; }
.w-add-3min { --w-add-min-1: 3px; }
.w-add-4min { --w-add-min-1: 4px; }
.w-add-5min { --w-add-min-1: 5px; }
.w-add-6min { --w-add-min-1: 6px; }
.w-add-7min { --w-add-min-1: 7px; }
.w-add-8min { --w-add-min-1: 8px; }
.w-add-9min { --w-add-min-1: 9px; }