.w-add-1p { --w-a-p: 1%; }
.w-add-2p { --w-a-p: 2%; }
.w-add-3p { --w-a-p: 3%; }
.w-add-4p { --w-a-p: 4%; }
.w-add-5p { --w-a-p: 5%; }
.w-add-6p { --w-a-p: 6%; }
.w-add-7p { --w-a-p: 7%; }
.w-add-8p { --w-a-p: 8%; }
.w-add-9p { --w-a-p: 9%; }