.w-add-1min { --w-a-min: 1px; }
.w-add-2min { --w-a-min: 2px; }
.w-add-3min { --w-a-min: 3px; }
.w-add-4min { --w-a-min: 4px; }
.w-add-5min { --w-a-min: 5px; }
.w-add-6min { --w-a-min: 6px; }
.w-add-7min { --w-a-min: 7px; }
.w-add-8min { --w-a-min: 8px; }
.w-add-9min { --w-a-min: 9px; }